//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laser.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MinV {
            get {
                return ((double)(this["MinV"]));
            }
            set {
                this["MinV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80000")]
        public double MaxV {
            get {
                return ((double)(this["MaxV"]));
            }
            set {
                this["MaxV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public double MinT {
            get {
                return ((double)(this["MinT"]));
            }
            set {
                this["MinT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double MaxT {
            get {
                return ((double)(this["MaxT"]));
            }
            set {
                this["MaxT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ActV {
            get {
                return ((double)(this["ActV"]));
            }
            set {
                this["ActV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double ActT {
            get {
                return ((double)(this["ActT"]));
            }
            set {
                this["ActT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double StepV {
            get {
                return ((double)(this["StepV"]));
            }
            set {
                this["StepV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double StepT {
            get {
                return ((double)(this["StepT"]));
            }
            set {
                this["StepT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int TStepT {
            get {
                return ((int)(this["TStepT"]));
            }
            set {
                this["TStepT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int TStepV {
            get {
                return ((int)(this["TStepV"]));
            }
            set {
                this["TStepV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda1MinV {
            get {
                return ((double)(this["Dioda1MinV"]));
            }
            set {
                this["Dioda1MinV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public double Dioda1MaxV {
            get {
                return ((double)(this["Dioda1MaxV"]));
            }
            set {
                this["Dioda1MaxV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double Dioda1MinT {
            get {
                return ((double)(this["Dioda1MinT"]));
            }
            set {
                this["Dioda1MinT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public double Dioda1MaxT {
            get {
                return ((double)(this["Dioda1MaxT"]));
            }
            set {
                this["Dioda1MaxT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ChecklistDiode {
            get {
                return ((int)(this["ChecklistDiode"]));
            }
            set {
                this["ChecklistDiode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2MinV {
            get {
                return ((double)(this["Dioda2MinV"]));
            }
            set {
                this["Dioda2MinV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public double Dioda2MaxV {
            get {
                return ((double)(this["Dioda2MaxV"]));
            }
            set {
                this["Dioda2MaxV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double Dioda2MinT {
            get {
                return ((double)(this["Dioda2MinT"]));
            }
            set {
                this["Dioda2MinT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public double Dioda2MaxT {
            get {
                return ((double)(this["Dioda2MaxT"]));
            }
            set {
                this["Dioda2MaxT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3MinV {
            get {
                return ((double)(this["Dioda3MinV"]));
            }
            set {
                this["Dioda3MinV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3MaxV {
            get {
                return ((double)(this["Dioda3MaxV"]));
            }
            set {
                this["Dioda3MaxV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3MinT {
            get {
                return ((double)(this["Dioda3MinT"]));
            }
            set {
                this["Dioda3MinT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3MaxT {
            get {
                return ((double)(this["Dioda3MaxT"]));
            }
            set {
                this["Dioda3MaxT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MinE {
            get {
                return ((double)(this["MinE"]));
            }
            set {
                this["MinE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MaxE {
            get {
                return ((double)(this["MaxE"]));
            }
            set {
                this["MaxE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double StepE {
            get {
                return ((double)(this["StepE"]));
            }
            set {
                this["StepE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EStepT {
            get {
                return ((int)(this["EStepT"]));
            }
            set {
                this["EStepT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EStepV {
            get {
                return ((int)(this["EStepV"]));
            }
            set {
                this["EStepV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MinQ {
            get {
                return ((double)(this["MinQ"]));
            }
            set {
                this["MinQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MaxQ {
            get {
                return ((double)(this["MaxQ"]));
            }
            set {
                this["MaxQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double StepQ {
            get {
                return ((double)(this["StepQ"]));
            }
            set {
                this["StepQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int QStepT {
            get {
                return ((int)(this["QStepT"]));
            }
            set {
                this["QStepT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int QStepV {
            get {
                return ((int)(this["QStepV"]));
            }
            set {
                this["QStepV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MinK {
            get {
                return ((double)(this["MinK"]));
            }
            set {
                this["MinK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MaxK {
            get {
                return ((double)(this["MaxK"]));
            }
            set {
                this["MaxK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double StepK {
            get {
                return ((double)(this["StepK"]));
            }
            set {
                this["StepK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int KStepT {
            get {
                return ((int)(this["KStepT"]));
            }
            set {
                this["KStepT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int KStepV {
            get {
                return ((int)(this["KStepV"]));
            }
            set {
                this["KStepV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MinW {
            get {
                return ((double)(this["MinW"]));
            }
            set {
                this["MinW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MaxW {
            get {
                return ((double)(this["MaxW"]));
            }
            set {
                this["MaxW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double StepW {
            get {
                return ((double)(this["StepW"]));
            }
            set {
                this["StepW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WStepT {
            get {
                return ((int)(this["WStepT"]));
            }
            set {
                this["WStepT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WStepV {
            get {
                return ((int)(this["WStepV"]));
            }
            set {
                this["WStepV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public short ScalingParameter {
            get {
                return ((short)(this["ScalingParameter"]));
            }
            set {
                this["ScalingParameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TriggerParameter {
            get {
                return ((bool)(this["TriggerParameter"]));
            }
            set {
                this["TriggerParameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short Graphsettingoption {
            get {
                return ((short)(this["Graphsettingoption"]));
            }
            set {
                this["Graphsettingoption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Graphsettingtype {
            get {
                return ((bool)(this["Graphsettingtype"]));
            }
            set {
                this["Graphsettingtype"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.000171972")]
        public double Dioda1A1LOWcm {
            get {
                return ((double)(this["Dioda1A1LOWcm"]));
            }
            set {
                this["Dioda1A1LOWcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.00922")]
        public double Dioda1B1LOWcm {
            get {
                return ((double)(this["Dioda1B1LOWcm"]));
            }
            set {
                this["Dioda1B1LOWcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1.0296")]
        public double Dioda1C1LOWcm {
            get {
                return ((double)(this["Dioda1C1LOWcm"]));
            }
            set {
                this["Dioda1C1LOWcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12851.27013")]
        public double Dioda1D1LOWcm {
            get {
                return ((double)(this["Dioda1D1LOWcm"]));
            }
            set {
                this["Dioda1D1LOWcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.04084E-05")]
        public double Dioda1A1LOWnm {
            get {
                return ((double)(this["Dioda1A1LOWnm"]));
            }
            set {
                this["Dioda1A1LOWnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.000554599")]
        public double Dioda1B1LOWnm {
            get {
                return ((double)(this["Dioda1B1LOWnm"]));
            }
            set {
                this["Dioda1B1LOWnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.06237")]
        public double Dioda1C1LOWnm {
            get {
                return ((double)(this["Dioda1C1LOWnm"]));
            }
            set {
                this["Dioda1C1LOWnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("778.13318")]
        public double Dioda1D1LOWnm {
            get {
                return ((double)(this["Dioda1D1LOWnm"]));
            }
            set {
                this["Dioda1D1LOWnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-5.1556E-06")]
        public double Dioda1A1LOWTHz {
            get {
                return ((double)(this["Dioda1A1LOWTHz"]));
            }
            set {
                this["Dioda1A1LOWTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.000276371")]
        public double Dioda1B1LOWTHz {
            get {
                return ((double)(this["Dioda1B1LOWTHz"]));
            }
            set {
                this["Dioda1B1LOWTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.03087")]
        public double Dioda1C1LOWTHz {
            get {
                return ((double)(this["Dioda1C1LOWTHz"]));
            }
            set {
                this["Dioda1C1LOWTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("385.27139")]
        public double Dioda1D1LOWTHz {
            get {
                return ((double)(this["Dioda1D1LOWTHz"]));
            }
            set {
                this["Dioda1D1LOWTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.000135127")]
        public double Dioda1A1MIDcm {
            get {
                return ((double)(this["Dioda1A1MIDcm"]));
            }
            set {
                this["Dioda1A1MIDcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.007")]
        public double Dioda1B1MIDcm {
            get {
                return ((double)(this["Dioda1B1MIDcm"]));
            }
            set {
                this["Dioda1B1MIDcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.98234")]
        public double Dioda1C1MIDcm {
            get {
                return ((double)(this["Dioda1C1MIDcm"]));
            }
            set {
                this["Dioda1C1MIDcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12850.79027")]
        public double Dioda1D1MIDcm {
            get {
                return ((double)(this["Dioda1D1MIDcm"]));
            }
            set {
                this["Dioda1D1MIDcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8.24117E-06")]
        public double Dioda1A1MIDnm {
            get {
                return ((double)(this["Dioda1A1MIDnm"]));
            }
            set {
                this["Dioda1A1MIDnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.000423721")]
        public double Dioda1B1MIDnm {
            get {
                return ((double)(this["Dioda1B1MIDnm"]));
            }
            set {
                this["Dioda1B1MIDnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5956")]
        public double Dioda1C1MIDnm {
            get {
                return ((double)(this["Dioda1C1MIDnm"]));
            }
            set {
                this["Dioda1C1MIDnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("778.16178")]
        public double Dioda1D1MIDnm {
            get {
                return ((double)(this["Dioda1D1MIDnm"]));
            }
            set {
                this["Dioda1D1MIDnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-4.05101E-06")]
        public double Dioda1A1MIDTHz {
            get {
                return ((double)(this["Dioda1A1MIDTHz"]));
            }
            set {
                this["Dioda1A1MIDTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.000209782")]
        public double Dioda1B1MIDTHz {
            get {
                return ((double)(this["Dioda1B1MIDTHz"]));
            }
            set {
                this["Dioda1B1MIDTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.02945")]
        public double Dioda1C1MIDTHz {
            get {
                return ((double)(this["Dioda1C1MIDTHz"]));
            }
            set {
                this["Dioda1C1MIDTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("385.257")]
        public double Dioda1D1MIDTHz {
            get {
                return ((double)(this["Dioda1D1MIDTHz"]));
            }
            set {
                this["Dioda1D1MIDTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-4.41143E-05")]
        public double Dioda1A1HIGHcm {
            get {
                return ((double)(this["Dioda1A1HIGHcm"]));
            }
            set {
                this["Dioda1A1HIGHcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.00441")]
        public double Dioda1B1HIGHcm {
            get {
                return ((double)(this["Dioda1B1HIGHcm"]));
            }
            set {
                this["Dioda1B1HIGHcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.53475")]
        public double Dioda1C1HIGHcm {
            get {
                return ((double)(this["Dioda1C1HIGHcm"]));
            }
            set {
                this["Dioda1C1HIGHcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12844.97813")]
        public double Dioda1D1HIGHcm {
            get {
                return ((double)(this["Dioda1D1HIGHcm"]));
            }
            set {
                this["Dioda1D1HIGHcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.7706E-06")]
        public double Dioda1A1HIGHnm {
            get {
                return ((double)(this["Dioda1A1HIGHnm"]));
            }
            set {
                this["Dioda1A1HIGHnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.000264008")]
        public double Dioda1B1HIGHnm {
            get {
                return ((double)(this["Dioda1B1HIGHnm"]));
            }
            set {
                this["Dioda1B1HIGHnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.03252")]
        public double Dioda1C1HIGHnm {
            get {
                return ((double)(this["Dioda1C1HIGHnm"]));
            }
            set {
                this["Dioda1C1HIGHnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("778.51336")]
        public double Dioda1D1HIGHnm {
            get {
                return ((double)(this["Dioda1D1HIGHnm"]));
            }
            set {
                this["Dioda1D1HIGHnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1.32251E-06")]
        public double Dioda1A1HIGHTHz {
            get {
                return ((double)(this["Dioda1A1HIGHTHz"]));
            }
            set {
                this["Dioda1A1HIGHTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.000132141")]
        public double Dioda1B1HIGHTHz {
            get {
                return ((double)(this["Dioda1B1HIGHTHz"]));
            }
            set {
                this["Dioda1B1HIGHTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.01603")]
        public double Dioda1C1HIGHTHz {
            get {
                return ((double)(this["Dioda1C1HIGHTHz"]));
            }
            set {
                this["Dioda1C1HIGHTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("385.08276")]
        public double Dioda1D1HIGHTHz {
            get {
                return ((double)(this["Dioda1D1HIGHTHz"]));
            }
            set {
                this["Dioda1D1HIGHTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.000172815")]
        public double Dioda1A1HIGHHcm {
            get {
                return ((double)(this["Dioda1A1HIGHHcm"]));
            }
            set {
                this["Dioda1A1HIGHHcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.00953")]
        public double Dioda1B1HIGHHcm {
            get {
                return ((double)(this["Dioda1B1HIGHHcm"]));
            }
            set {
                this["Dioda1B1HIGHHcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1.04788")]
        public double Dioda1C1HIGHHcm {
            get {
                return ((double)(this["Dioda1C1HIGHHcm"]));
            }
            set {
                this["Dioda1C1HIGHHcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12850.21943")]
        public double Dioda1D1HIGHHcm {
            get {
                return ((double)(this["Dioda1D1HIGHHcm"]));
            }
            set {
                this["Dioda1D1HIGHHcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.05122E-05")]
        public double Dioda1A1HIGHHnm {
            get {
                return ((double)(this["Dioda1A1HIGHHnm"]));
            }
            set {
                this["Dioda1A1HIGHHnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.000575543")]
        public double Dioda1B1HIGHHnm {
            get {
                return ((double)(this["Dioda1B1HIGHHnm"]));
            }
            set {
                this["Dioda1B1HIGHHnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0635")]
        public double Dioda1C1HIGHHnm {
            get {
                return ((double)(this["Dioda1C1HIGHHnm"]));
            }
            set {
                this["Dioda1C1HIGHHnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("778.19669")]
        public double Dioda1D1HIGHHnm {
            get {
                return ((double)(this["Dioda1D1HIGHHnm"]));
            }
            set {
                this["Dioda1D1HIGHHnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-5.18085E-06")]
        public double Dioda1A1HIGHHTHz {
            get {
                return ((double)(this["Dioda1A1HIGHHTHz"]));
            }
            set {
                this["Dioda1A1HIGHHTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.000285591")]
        public double Dioda1B1HIGHHTHz {
            get {
                return ((double)(this["Dioda1B1HIGHHTHz"]));
            }
            set {
                this["Dioda1B1HIGHHTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.03141")]
        public double Dioda1C1HIGHHTHz {
            get {
                return ((double)(this["Dioda1C1HIGHHTHz"]));
            }
            set {
                this["Dioda1C1HIGHHTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("385.23989")]
        public double Dioda1D1HIGHHTHz {
            get {
                return ((double)(this["Dioda1D1HIGHHTHz"]));
            }
            set {
                this["Dioda1D1HIGHHTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public double Dioda2A1LOWcm {
            get {
                return ((double)(this["Dioda2A1LOWcm"]));
            }
            set {
                this["Dioda2A1LOWcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2B1LOWcm {
            get {
                return ((double)(this["Dioda2B1LOWcm"]));
            }
            set {
                this["Dioda2B1LOWcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2C1LOWcm {
            get {
                return ((double)(this["Dioda2C1LOWcm"]));
            }
            set {
                this["Dioda2C1LOWcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2D1LOWcm {
            get {
                return ((double)(this["Dioda2D1LOWcm"]));
            }
            set {
                this["Dioda2D1LOWcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2A1LOWnm {
            get {
                return ((double)(this["Dioda2A1LOWnm"]));
            }
            set {
                this["Dioda2A1LOWnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2B1LOWnm {
            get {
                return ((double)(this["Dioda2B1LOWnm"]));
            }
            set {
                this["Dioda2B1LOWnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2C1LOWnm {
            get {
                return ((double)(this["Dioda2C1LOWnm"]));
            }
            set {
                this["Dioda2C1LOWnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2D1LOWnm {
            get {
                return ((double)(this["Dioda2D1LOWnm"]));
            }
            set {
                this["Dioda2D1LOWnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2A1LOWTHz {
            get {
                return ((double)(this["Dioda2A1LOWTHz"]));
            }
            set {
                this["Dioda2A1LOWTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2B1LOWTHz {
            get {
                return ((double)(this["Dioda2B1LOWTHz"]));
            }
            set {
                this["Dioda2B1LOWTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2C1LOWTHz {
            get {
                return ((double)(this["Dioda2C1LOWTHz"]));
            }
            set {
                this["Dioda2C1LOWTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2D1LOWTHz {
            get {
                return ((double)(this["Dioda2D1LOWTHz"]));
            }
            set {
                this["Dioda2D1LOWTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2A1MIDcm {
            get {
                return ((double)(this["Dioda2A1MIDcm"]));
            }
            set {
                this["Dioda2A1MIDcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2B1MIDcm {
            get {
                return ((double)(this["Dioda2B1MIDcm"]));
            }
            set {
                this["Dioda2B1MIDcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2C1MIDcm {
            get {
                return ((double)(this["Dioda2C1MIDcm"]));
            }
            set {
                this["Dioda2C1MIDcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2D1MIDcm {
            get {
                return ((double)(this["Dioda2D1MIDcm"]));
            }
            set {
                this["Dioda2D1MIDcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2A1MIDnm {
            get {
                return ((double)(this["Dioda2A1MIDnm"]));
            }
            set {
                this["Dioda2A1MIDnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2B1MIDnm {
            get {
                return ((double)(this["Dioda2B1MIDnm"]));
            }
            set {
                this["Dioda2B1MIDnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2C1MIDnm {
            get {
                return ((double)(this["Dioda2C1MIDnm"]));
            }
            set {
                this["Dioda2C1MIDnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2D1MIDnm {
            get {
                return ((double)(this["Dioda2D1MIDnm"]));
            }
            set {
                this["Dioda2D1MIDnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2A1MIDTHz {
            get {
                return ((double)(this["Dioda2A1MIDTHz"]));
            }
            set {
                this["Dioda2A1MIDTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2B1MIDTHz {
            get {
                return ((double)(this["Dioda2B1MIDTHz"]));
            }
            set {
                this["Dioda2B1MIDTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2C1MIDTHz {
            get {
                return ((double)(this["Dioda2C1MIDTHz"]));
            }
            set {
                this["Dioda2C1MIDTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2D1MIDTHz {
            get {
                return ((double)(this["Dioda2D1MIDTHz"]));
            }
            set {
                this["Dioda2D1MIDTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2A1HIGHcm {
            get {
                return ((double)(this["Dioda2A1HIGHcm"]));
            }
            set {
                this["Dioda2A1HIGHcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2B1HIGHcm {
            get {
                return ((double)(this["Dioda2B1HIGHcm"]));
            }
            set {
                this["Dioda2B1HIGHcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2C1HIGHcm {
            get {
                return ((double)(this["Dioda2C1HIGHcm"]));
            }
            set {
                this["Dioda2C1HIGHcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2D1HIGHcm {
            get {
                return ((double)(this["Dioda2D1HIGHcm"]));
            }
            set {
                this["Dioda2D1HIGHcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2A1HIGHnm {
            get {
                return ((double)(this["Dioda2A1HIGHnm"]));
            }
            set {
                this["Dioda2A1HIGHnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2B1HIGHnm {
            get {
                return ((double)(this["Dioda2B1HIGHnm"]));
            }
            set {
                this["Dioda2B1HIGHnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2C1HIGHnm {
            get {
                return ((double)(this["Dioda2C1HIGHnm"]));
            }
            set {
                this["Dioda2C1HIGHnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2D1HIGHnm {
            get {
                return ((double)(this["Dioda2D1HIGHnm"]));
            }
            set {
                this["Dioda2D1HIGHnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2A1HIGHTHz {
            get {
                return ((double)(this["Dioda2A1HIGHTHz"]));
            }
            set {
                this["Dioda2A1HIGHTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2B1HIGHTHz {
            get {
                return ((double)(this["Dioda2B1HIGHTHz"]));
            }
            set {
                this["Dioda2B1HIGHTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2C1HIGHTHz {
            get {
                return ((double)(this["Dioda2C1HIGHTHz"]));
            }
            set {
                this["Dioda2C1HIGHTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2D1HIGHTHz {
            get {
                return ((double)(this["Dioda2D1HIGHTHz"]));
            }
            set {
                this["Dioda2D1HIGHTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2A1HIGHHcm {
            get {
                return ((double)(this["Dioda2A1HIGHHcm"]));
            }
            set {
                this["Dioda2A1HIGHHcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2B1HIGHHcm {
            get {
                return ((double)(this["Dioda2B1HIGHHcm"]));
            }
            set {
                this["Dioda2B1HIGHHcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2C1HIGHHcm {
            get {
                return ((double)(this["Dioda2C1HIGHHcm"]));
            }
            set {
                this["Dioda2C1HIGHHcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2D1HIGHHcm {
            get {
                return ((double)(this["Dioda2D1HIGHHcm"]));
            }
            set {
                this["Dioda2D1HIGHHcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2A1HIGHHnm {
            get {
                return ((double)(this["Dioda2A1HIGHHnm"]));
            }
            set {
                this["Dioda2A1HIGHHnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2B1HIGHHnm {
            get {
                return ((double)(this["Dioda2B1HIGHHnm"]));
            }
            set {
                this["Dioda2B1HIGHHnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2C1HIGHHnm {
            get {
                return ((double)(this["Dioda2C1HIGHHnm"]));
            }
            set {
                this["Dioda2C1HIGHHnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2D1HIGHHnm {
            get {
                return ((double)(this["Dioda2D1HIGHHnm"]));
            }
            set {
                this["Dioda2D1HIGHHnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2A1HIGHHTHz {
            get {
                return ((double)(this["Dioda2A1HIGHHTHz"]));
            }
            set {
                this["Dioda2A1HIGHHTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2B1HIGHHTHz {
            get {
                return ((double)(this["Dioda2B1HIGHHTHz"]));
            }
            set {
                this["Dioda2B1HIGHHTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2C1HIGHHTHz {
            get {
                return ((double)(this["Dioda2C1HIGHHTHz"]));
            }
            set {
                this["Dioda2C1HIGHHTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda2D1HIGHHTHz {
            get {
                return ((double)(this["Dioda2D1HIGHHTHz"]));
            }
            set {
                this["Dioda2D1HIGHHTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3A1LOWcm {
            get {
                return ((double)(this["Dioda3A1LOWcm"]));
            }
            set {
                this["Dioda3A1LOWcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3B1LOWcm {
            get {
                return ((double)(this["Dioda3B1LOWcm"]));
            }
            set {
                this["Dioda3B1LOWcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3C1LOWcm {
            get {
                return ((double)(this["Dioda3C1LOWcm"]));
            }
            set {
                this["Dioda3C1LOWcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3D1LOWcm {
            get {
                return ((double)(this["Dioda3D1LOWcm"]));
            }
            set {
                this["Dioda3D1LOWcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3A1LOWnm {
            get {
                return ((double)(this["Dioda3A1LOWnm"]));
            }
            set {
                this["Dioda3A1LOWnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3B1LOWnm {
            get {
                return ((double)(this["Dioda3B1LOWnm"]));
            }
            set {
                this["Dioda3B1LOWnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3C1LOWnm {
            get {
                return ((double)(this["Dioda3C1LOWnm"]));
            }
            set {
                this["Dioda3C1LOWnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3D1LOWnm {
            get {
                return ((double)(this["Dioda3D1LOWnm"]));
            }
            set {
                this["Dioda3D1LOWnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3A1LOWTHz {
            get {
                return ((double)(this["Dioda3A1LOWTHz"]));
            }
            set {
                this["Dioda3A1LOWTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3B1LOWTHz {
            get {
                return ((double)(this["Dioda3B1LOWTHz"]));
            }
            set {
                this["Dioda3B1LOWTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3C1LOWTHz {
            get {
                return ((double)(this["Dioda3C1LOWTHz"]));
            }
            set {
                this["Dioda3C1LOWTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3D1LOWTHz {
            get {
                return ((double)(this["Dioda3D1LOWTHz"]));
            }
            set {
                this["Dioda3D1LOWTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3A1MIDcm {
            get {
                return ((double)(this["Dioda3A1MIDcm"]));
            }
            set {
                this["Dioda3A1MIDcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3B1MIDcm {
            get {
                return ((double)(this["Dioda3B1MIDcm"]));
            }
            set {
                this["Dioda3B1MIDcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3C1MIDcm {
            get {
                return ((double)(this["Dioda3C1MIDcm"]));
            }
            set {
                this["Dioda3C1MIDcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3D1MIDcm {
            get {
                return ((double)(this["Dioda3D1MIDcm"]));
            }
            set {
                this["Dioda3D1MIDcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3A1MIDnm {
            get {
                return ((double)(this["Dioda3A1MIDnm"]));
            }
            set {
                this["Dioda3A1MIDnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3B1MIDnm {
            get {
                return ((double)(this["Dioda3B1MIDnm"]));
            }
            set {
                this["Dioda3B1MIDnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3C1MIDnm {
            get {
                return ((double)(this["Dioda3C1MIDnm"]));
            }
            set {
                this["Dioda3C1MIDnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3D1MIDnm {
            get {
                return ((double)(this["Dioda3D1MIDnm"]));
            }
            set {
                this["Dioda3D1MIDnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3A1MIDTHz {
            get {
                return ((double)(this["Dioda3A1MIDTHz"]));
            }
            set {
                this["Dioda3A1MIDTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3B1MIDTHz {
            get {
                return ((double)(this["Dioda3B1MIDTHz"]));
            }
            set {
                this["Dioda3B1MIDTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3C1MIDTHz {
            get {
                return ((double)(this["Dioda3C1MIDTHz"]));
            }
            set {
                this["Dioda3C1MIDTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3D1MIDTHz {
            get {
                return ((double)(this["Dioda3D1MIDTHz"]));
            }
            set {
                this["Dioda3D1MIDTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3A1HIGHcm {
            get {
                return ((double)(this["Dioda3A1HIGHcm"]));
            }
            set {
                this["Dioda3A1HIGHcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3B1HIGHcm {
            get {
                return ((double)(this["Dioda3B1HIGHcm"]));
            }
            set {
                this["Dioda3B1HIGHcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3C1HIGHcm {
            get {
                return ((double)(this["Dioda3C1HIGHcm"]));
            }
            set {
                this["Dioda3C1HIGHcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3D1HIGHcm {
            get {
                return ((double)(this["Dioda3D1HIGHcm"]));
            }
            set {
                this["Dioda3D1HIGHcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3A1HIGHnm {
            get {
                return ((double)(this["Dioda3A1HIGHnm"]));
            }
            set {
                this["Dioda3A1HIGHnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3B1HIGHnm {
            get {
                return ((double)(this["Dioda3B1HIGHnm"]));
            }
            set {
                this["Dioda3B1HIGHnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3C1HIGHnm {
            get {
                return ((double)(this["Dioda3C1HIGHnm"]));
            }
            set {
                this["Dioda3C1HIGHnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3D1HIGHnm {
            get {
                return ((double)(this["Dioda3D1HIGHnm"]));
            }
            set {
                this["Dioda3D1HIGHnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3A1HIGHTHz {
            get {
                return ((double)(this["Dioda3A1HIGHTHz"]));
            }
            set {
                this["Dioda3A1HIGHTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3B1HIGHTHz {
            get {
                return ((double)(this["Dioda3B1HIGHTHz"]));
            }
            set {
                this["Dioda3B1HIGHTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3C1HIGHTHz {
            get {
                return ((double)(this["Dioda3C1HIGHTHz"]));
            }
            set {
                this["Dioda3C1HIGHTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3D1HIGHTHz {
            get {
                return ((double)(this["Dioda3D1HIGHTHz"]));
            }
            set {
                this["Dioda3D1HIGHTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3A1HIGHHcm {
            get {
                return ((double)(this["Dioda3A1HIGHHcm"]));
            }
            set {
                this["Dioda3A1HIGHHcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3B1HIGHHcm {
            get {
                return ((double)(this["Dioda3B1HIGHHcm"]));
            }
            set {
                this["Dioda3B1HIGHHcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3C1HIGHHcm {
            get {
                return ((double)(this["Dioda3C1HIGHHcm"]));
            }
            set {
                this["Dioda3C1HIGHHcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3D1HIGHHcm {
            get {
                return ((double)(this["Dioda3D1HIGHHcm"]));
            }
            set {
                this["Dioda3D1HIGHHcm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3A1HIGHHnm {
            get {
                return ((double)(this["Dioda3A1HIGHHnm"]));
            }
            set {
                this["Dioda3A1HIGHHnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3B1HIGHHnm {
            get {
                return ((double)(this["Dioda3B1HIGHHnm"]));
            }
            set {
                this["Dioda3B1HIGHHnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3C1HIGHHnm {
            get {
                return ((double)(this["Dioda3C1HIGHHnm"]));
            }
            set {
                this["Dioda3C1HIGHHnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3D1HIGHHnm {
            get {
                return ((double)(this["Dioda3D1HIGHHnm"]));
            }
            set {
                this["Dioda3D1HIGHHnm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3A1HIGHHTHz {
            get {
                return ((double)(this["Dioda3A1HIGHHTHz"]));
            }
            set {
                this["Dioda3A1HIGHHTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3B1HIGHHTHz {
            get {
                return ((double)(this["Dioda3B1HIGHHTHz"]));
            }
            set {
                this["Dioda3B1HIGHHTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3C1HIGHHTHz {
            get {
                return ((double)(this["Dioda3C1HIGHHTHz"]));
            }
            set {
                this["Dioda3C1HIGHHTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Dioda3D1HIGHHTHz {
            get {
                return ((double)(this["Dioda3D1HIGHHTHz"]));
            }
            set {
                this["Dioda3D1HIGHHTHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ChosenDiode {
            get {
                return ((int)(this["ChosenDiode"]));
            }
            set {
                this["ChosenDiode"] = value;
            }
        }
    }
}
